version: '3.8'

services:
  forming-app:
    build: .
    container_name: forming-app
    ports:
      - "3000:3000"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
