version: '3.8'

services:
  forming-app:
    build: .
    container_name: forming-app
    ports:
      - "3000:3000"
    environment:
      # KOREKSI 1: Gunakan nama container, JANGAN IP angka
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_USER=postgres
      # Pastikan password ini benar sesuai settingan postgres container Anda
      - DB_PASSWORD=password_rahasia_anda 
      - DB_NAME=servfi
      
      # SARAN TAMBAHAN: Masukkan config MQTT sekalian jika app butuh
      - MQTT_HOST=emqx
      - MQTT_PORT=1883
      
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
      - production_network

# KOREKSI 2: Bagian ini harus di paling kiri (sejajar dengan 'services')
networks:
  production_network:
    name: servfor_iot-net
    external: true